const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Behaviors.Car,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.sliderbar,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.List,
		C3.Plugins.SVGPicture,
		C3.Behaviors.Flash,
		C3.Plugins.qrcode,
		C3.Plugins.Internationalization,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Car.Acts.Stop,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Cnds.IsPaused,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Cnds.OnPlaybackEvent,
		C3.Plugins.video.Acts.SetVolume
	];
};
self.C3_JsPropNameTable = [
	{GC橋式起重機: 0},
	{橋式起重機_停車點: 0},
	{橋式起重機_側面: 0},
	{通關: 0},
	{橋式起重機_地圖: 0},
	{左右: 0},
	{橋式起重機_後: 0},
	{橋式起重機_操作解釋頁面2_上下左右: 0},
	{橋式起重機_操作解釋頁面2_鎖2: 0},
	{橋式起重機_操作解釋頁面2_鬆: 0},
	{說明選單_說明文字: 0},
	{橋式起重機_通關: 0},
	{橋式起重機_導航欄: 0},
	{橋式起重機_導航欄2: 0},
	{場租費: 0},
	{裝卸費: 0},
	{冷凍櫃費用: 0},
	{倉庫費用: 0},
	{貨櫃清潔及維修費用: 0},
	{理貨費: 0},
	{解答: 0},
	{是: 0},
	{否: 0},
	{場租費2: 0},
	{冷凍櫃費用2: 0},
	{冷凍櫃費用3: 0},
	{BG: 0},
	{拖放: 0},
	{實體: 0},
	{拖車: 0},
	{"8方向": 0},
	{空櫃堆高機: 0},
	{正弦: 0},
	{方向盤: 0},
	{鍵盤: 0},
	{地板: 0},
	{空櫃堆高機_地圖: 0},
	{拖車板車: 0},
	{接觸: 0},
	{平台: 0},
	{空櫃: 0},
	{上下: 0},
	{空櫃夾: 0},
	{Sprite4: 0},
	{鎖: 0},
	{鬆: 0},
	{Touch: 0},
	{軌道式門式起重機_地圖_白邊: 0},
	{輪胎式門式起重機_地圖: 0},
	{輪型跨載機_地圖_白邊: 0},
	{重櫃堆高機_地圖: 0},
	{倉庫堆高機_地圖: 0},
	{空櫃起重機_停車點: 0},
	{船: 0},
	{夾子: 0},
	{固定: 0},
	{繩子: 0},
	{滑塊: 0},
	{輪胎式門式起重機: 0},
	{軌道式門式起重機_後: 0},
	{貨櫃堆1: 0},
	{非實體車: 0},
	{軌道式門式起重機_側面: 0},
	{車: 0},
	{輪胎式門式起重機_俯視: 0},
	{拖車板車俯視: 0},
	{貨櫃_俯視: 0},
	{輪胎式門式起重機_側面: 0},
	{Sprite2: 0},
	{貨櫃堆_俯視: 0},
	{輪型跨載機_側面: 0},
	{Sprite3: 0},
	{Sprite5: 0},
	{重櫃夾: 0},
	{重櫃堆高機: 0},
	{繩子2: 0},
	{大標題: 0},
	{標題: 0},
	{按鈕: 0},
	{Sprite7: 0},
	{開始: 0},
	{音頻: 0},
	{視頻: 0},
	{Sprite8: 0},
	{變量1: 0},
	{next: 0},
	{home: 0},
	{說明icon: 0},
	{目錄頁_CH1: 0},
	{目錄頁_CH2: 0},
	{目錄頁_CH3: 0},
	{選擇章節: 0},
	{目錄頁_CH1_B: 0},
	{目錄頁_CH2_B: 0},
	{目錄頁_CH3_B: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Text2: 0},
	{鍵盤左: 0},
	{倉庫堆高機: 0},
	{倉庫堆高機_夾子: 0},
	{沒載貨櫃的車_左側: 0},
	{Text: 0},
	{裝卸費和理貨費_確認: 0},
	{場租費_確認: 0},
	{冷凍櫃費用_確認: 0},
	{倉庫費用_確認: 0},
	{貨櫃清潔及維修費用_確認: 0},
	{理貨費_確認: 0},
	{Text3: 0},
	{Text4: 0},
	{說明: 0},
	{體驗: 0},
	{Sprite: 0},
	{門式起重機_測驗選項: 0},
	{橋式起重機_測驗選項: 0},
	{重櫃堆高機_測驗選項: 0},
	{倉庫堆高機_測驗選項: 0},
	{裝卸機_測驗選項: 0},
	{輪型跨載機_測驗選項: 0},
	{空櫃堆高機_測驗選項: 0},
	{拖車_測驗選項: 0},
	{按鈕底部樣式: 0},
	{視頻2: 0},
	{滑動條: 0},
	{播放: 0},
	{暫停: 0},
	{大地圖: 0},
	{Sprite17: 0},
	{輪型跨載機_地圖2: 0},
	{軌道式門式起重機_地圖: 0},
	{空櫃堆高機側: 0},
	{空櫃2: 0},
	{空櫃3: 0},
	{測驗: 0},
	{滑鼠: 0},
	{圈: 0},
	{叉叉: 0},
	{四題選擇_選項1: 0},
	{四題選擇_選項2: 0},
	{四題選擇_選項3: 0},
	{四題選擇_選項4: 0},
	{滑動條2: 0},
	{一號貨櫃人: 0},
	{位圖字體: 0},
	{回答: 0},
	{圖標_選單背景: 0},
	{圖標_選單說明: 0},
	{進入體驗按鈕: 0},
	{說明選單_標題: 0},
	{說明選單_進入體驗按鈕: 0},
	{分隔線: 0},
	{貨櫃一問答_ans: 0},
	{沒載貨櫃的車_右側: 0},
	{測驗icon: 0},
	{Bg2: 0},
	{重櫃堆高機_選項: 0},
	{空櫃堆高機_選項: 0},
	{倉庫堆高機_選項: 0},
	{Bg3: 0},
	{標題2: 0},
	{地圖_橋式起重機_小標: 0},
	{地圖_輪胎式門式起重機_小標: 0},
	{導航欄背景: 0},
	{輪胎式門式起重機_導航欄: 0},
	{空櫃堆高機_導航欄: 0},
	{重櫃堆高機_導航欄: 0},
	{輪型跨載機_導航欄: 0},
	{拖車_導航欄: 0},
	{倉庫堆高機_導航欄: 0},
	{軌道式門式起重機_導航欄: 0},
	{地圖_空櫃堆高機_小標: 0},
	{地圖_重櫃堆高機_小標: 0},
	{地圖_輪型跨載機_小標: 0},
	{地圖_拖車_小標: 0},
	{地圖_軌道式門式起重機_小標: 0},
	{地圖_倉庫堆高機_小標: 0},
	{Bg4: 0},
	{軌道式門式起重機_導航欄2: 0},
	{倉庫堆高機_導航欄2: 0},
	{輪胎式門式起重機_導航欄2: 0},
	{空櫃堆高機_導航欄2: 0},
	{重櫃堆高機_導航欄2: 0},
	{輪型跨載機_導航欄2: 0},
	{拖車_導航欄2: 0},
	{貨櫃堆2: 0},
	{重櫃堆高機_題目: 0},
	{按鈕底部樣式_橋式起重機: 0},
	{按鈕底部樣式_重櫃堆高機: 0},
	{按鈕底部樣式_輪型跨載機: 0},
	{按鈕底部樣式_拖車: 0},
	{框: 0},
	{Text5: 0},
	{列表: 0},
	{人: 0},
	{對話框: 0},
	{next2: 0},
	{選項1: 0},
	{選項2: 0},
	{選項3: 0},
	{選項4: 0},
	{選項5: 0},
	{選項6: 0},
	{選項7: 0},
	{Sprite16: 0},
	{櫃選: 0},
	{按鈕底部樣式_1: 0},
	{按鈕底部樣式_2: 0},
	{按鈕底部樣式_3: 0},
	{按鈕底部樣式_4: 0},
	{按鈕底部樣式_5: 0},
	{按鈕底部樣式_6: 0},
	{裝卸費_框: 0},
	{理貨費_框: 0},
	{場租費_框: 0},
	{場租費_框2: 0},
	{場租費_框3: 0},
	{場租費_框4: 0},
	{冷凍櫃費_框: 0},
	{清潔費_框: 0},
	{維修費_框: 0},
	{清潔費_框2: 0},
	{清潔費_框3: 0},
	{倉庫費_框: 0},
	{Sprite18: 0},
	{費用標籤_裝卸: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Text6: 0},
	{SVG: 0},
	{Sprite25: 0},
	{Text7: 0},
	{Sprite26: 0},
	{填答完成: 0},
	{Text8: 0},
	{選項8: 0},
	{按鈕底部樣式_7: 0},
	{貨櫃一作答: 0},
	{費用標籤_選中: 0},
	{CH3_說明文字: 0},
	{CH3_說明文字2: 0},
	{進度燈: 0},
	{進度燈2: 0},
	{進度燈3: 0},
	{進度燈4: 0},
	{進度燈5: 0},
	{進度燈6: 0},
	{船圖: 0},
	{箭頭: 0},
	{電腦: 0},
	{CH3_說明文字5: 0},
	{貨櫃堆3: 0},
	{CH3_說明文字6: 0},
	{按鈕框2: 0},
	{CH3_說明文字7: 0},
	{電腦2: 0},
	{信件: 0},
	{卸船櫃數單: 0},
	{備註: 0},
	{重櫃堆高機_右: 0},
	{貨站: 0},
	{出口貨物證明單: 0},
	{信件2: 0},
	{C1: 0},
	{C2: 0},
	{C3: 0},
	{出口小結: 0},
	{進口_分估計稅: 0},
	{進口_受理報關: 0},
	{進口_放行: 0},
	{進口_查驗: 0},
	{進口_海關辦理項目: 0},
	{進口_提貨: 0},
	{進口_登稅繳稅: 0},
	{進口_C1: 0},
	{進口_C2: 0},
	{進口_C3: 0},
	{C1遮罩: 0},
	{C2遮罩: 0},
	{出口_分估: 0},
	{出口_放行: 0},
	{出口_裝船: 0},
	{空格: 0},
	{空格_C1: 0},
	{空格_C2: 0},
	{空格_C3: 0},
	{勾勾: 0},
	{勾勾2: 0},
	{勾勾3: 0},
	{勾勾4: 0},
	{勾勾5: 0},
	{勾勾6: 0},
	{勾勾7: 0},
	{費用標籤_理貨: 0},
	{費用標籤_場租: 0},
	{費用標籤_冷凍: 0},
	{費用標籤_倉庫: 0},
	{費用標籤_清修: 0},
	{檢查清單: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{船2: 0},
	{空氣牆: 0},
	{閃爍: 0},
	{手: 0},
	{手2: 0},
	{空櫃4: 0},
	{貨櫃堆4: 0},
	{橋式_體驗結束: 0},
	{貨櫃堆5: 0},
	{空格2: 0},
	{說明選單_標題2: 0},
	{Sprite44: 0},
	{bg_目錄: 0},
	{上一頁: 0},
	{按鈕框3: 0},
	{Sprite45: 0},
	{鍵盤上: 0},
	{鍵盤下: 0},
	{鍵盤右: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{Sprite70: 0},
	{Sprite71: 0},
	{CH2: 0},
	{CH3: 0},
	{Sprite75: 0},
	{Sprite76: 0},
	{Sprite84: 0},
	{Sprite85: 0},
	{Sprite86: 0},
	{Sprite87: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{按鈕2: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{按鈕底部樣式_8: 0},
	{Sprite100: 0},
	{Sprite102: 0},
	{Sprite103: 0},
	{Sprite104: 0},
	{Sprite105: 0},
	{Sprite109: 0},
	{Sprite115: 0},
	{出口5船: 0},
	{Sprite120: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{空櫃堆高機_體驗結束: 0},
	{軌_體驗結束: 0},
	{輪_體驗結束: 0},
	{倉庫堆高機背景: 0},
	{輪胎_體驗結束: 0},
	{重_體驗結束: 0},
	{Sprite129: 0},
	{倉_體驗結束: 0},
	{按鈕底部樣式_輪型跨載機2: 0},
	{拖車_右邊介面: 0},
	{空櫃堆高機_右邊介面: 0},
	{軌道式門式起重機_右邊介面: 0},
	{重櫃堆高機_右邊介面: 0},
	{倉庫堆高機_右邊介面: 0},
	{第一章機具介紹_右邊介面: 0},
	{跨載機_右邊介面: 0},
	{輪胎式門式起重機_右邊介面: 0},
	{橋式起重機_右邊介面: 0},
	{進入體驗: 0},
	{CH1: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Sprite130: 0},
	{Sprite133: 0},
	{確認: 0},
	{Sprite135: 0},
	{進口3按鈕: 0},
	{進口4: 0},
	{Sprite138: 0},
	{Sprite139: 0},
	{Sprite140: 0},
	{Sprite141: 0},
	{比對完成: 0},
	{出口2按鈕: 0},
	{Sprite144: 0},
	{選1: 0},
	{選3: 0},
	{選2: 0},
	{選4: 0},
	{CH3_選2: 0},
	{CH3_選1: 0},
	{CH3_選3: 0},
	{CH3_選4: 0},
	{C3拖: 0},
	{C1拖: 0},
	{C2拖: 0},
	{Sprite159: 0},
	{出口3按鈕: 0},
	{Sprite161: 0},
	{Sprite162: 0},
	{Sprite163: 0},
	{是2: 0},
	{否2: 0},
	{"20尺": 0},
	{"30尺": 0},
	{"40尺": 0},
	{"45尺": 0},
	{Sprite170: 0},
	{重櫃_選: 0},
	{輪型_選: 0},
	{門式_選: 0},
	{橋式_選: 0},
	{Sprite175: 0},
	{Sprite176: 0},
	{Sprite177: 0},
	{Sprite178: 0},
	{叉叉2: 0},
	{叉叉3: 0},
	{拖標: 0},
	{空標: 0},
	{橋標: 0},
	{胎標: 0},
	{輪標: 0},
	{重標: 0},
	{倉標: 0},
	{軌標: 0},
	{開始測驗: 0},
	{開始檢查: 0},
	{Sprite164: 0},
	{測驗結束: 0},
	{Sprite145: 0},
	{紅心1: 0},
	{紅心2: 0},
	{紅心3: 0},
	{CH1_測驗說明: 0},
	{小叉: 0},
	{Sprite99: 0},
	{Sprite134: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{裝卸費說明: 0},
	{裝卸費說明2: 0},
	{裝卸費說明3: 0},
	{裝卸費說明4: 0},
	{裝卸費說明5: 0},
	{裝卸費說明6: 0},
	{裝卸費說明7: 0},
	{Sprite136: 0},
	{Sprite142: 0},
	{Sprite118: 0},
	{Sprite137: 0},
	{Sprite6: 0},
	{Sprite143: 0},
	{Sprite149: 0},
	{擋1: 0},
	{擋2: 0},
	{CH2_說明文字: 0},
	{CH2箭頭: 0},
	{next3: 0},
	{Sprite72: 0},
	{Sprite77: 0},
	{裝卸費說明8: 0},
	{"3岀": 0},
	{C13: 0},
	{第三章小選單: 0},
	{拖車_測: 0},
	{空櫃_測: 0},
	{裝_測: 0},
	{門_測: 0},
	{橋_測: 0},
	{輪跨_測: 0},
	{重_測: 0},
	{倉_測: 0},
	{Sprite110: 0},
	{Sprite111: 0},
	{手3: 0},
	{Sprite9: 0},
	{c1說明: 0},
	{c2說明: 0},
	{c3說明: 0},
	{c1說明出: 0},
	{c2說明出: 0},
	{c3說明出: 0},
	{Sprite165: 0},
	{next4: 0},
	{注視框: 0},
	{Sprite11: 0},
	{注視框2: 0},
	{注視框3: 0},
	{QRCode: 0},
	{Sprite10: 0},
	{Text9: 0},
	{QRCode2: 0},
	{Sprite12: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite78: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{Sprite82: 0},
	{Sprite83: 0},
	{Sprite88: 0},
	{Sprite91: 0},
	{上一頁2: 0},
	{QRCode3: 0},
	{Internationalization: 0},
	{Text10: 0},
	{空櫃AR: 0},
	{倉庫AR: 0},
	{輪型AR: 0},
	{拖車AR: 0},
	{重櫃AR: 0},
	{輪胎AR: 0},
	{橋式AR: 0},
	{軌道AR: 0},
	{Text11: 0},
	{紅心計數: 0},
	{答錯計數: 0},
	{解鎖第二章: 0},
	{控制說明選單AR: 0},
	{貨櫃1: 0},
	{貨櫃2: 0},
	{貨櫃3: 0},
	{貨櫃4: 0},
	{貨櫃5: 0},
	{貨櫃6: 0},
	{貨櫃7: 0},
	{貨車: 0},
	{控制說明選單: 0},
	{說明頁面: 0},
	{解鎖第三章: 0},
	{勾勾1: 0},
	{動畫燈: 0},
	{上進1: 0},
	{動畫燈3: 0},
	{上進2: 0},
	{動畫燈4: 0},
	{上進3: 0},
	{動畫燈2: 0},
	{動畫燈5: 0},
	{上進4: 0},
	{動畫燈6: 0},
	{動畫燈7: 0},
	{上進5: 0},
	{動畫燈8: 0},
	{動畫燈9: 0},
	{上進6: 0},
	{上進7: 0},
	{動畫燈10: 0},
	{上岀1: 0},
	{動畫燈11: 0},
	{上岀3: 0},
	{上岀2: 0},
	{動畫燈12: 0},
	{上一頁是否出口4: 0},
	{上岀5: 0},
	{上岀6: 0},
	{進口: 0},
	{出口: 0},
	{進口條件: 0},
	{出口條件: 0},
	{進口_c1: 0},
	{進口_c2: 0},
	{進口_c3: 0},
	{出口_C1: 0},
	{出口_C2: 0},
	{出口_C3: 0},
	{暫停播放: 0},
	{暫停播放2: 0},
	{暫停播放3: 0},
	{暫停播放4: 0},
	{暫停播放5: 0}
];

self.InstanceType = {
	GC橋式起重機: class extends self.ITextInstance {},
	橋式起重機_停車點: class extends self.ISpriteInstance {},
	橋式起重機_側面: class extends self.ISpriteInstance {},
	橋式起重機_地圖: class extends self.ISpriteInstance {},
	橋式起重機_後: class extends self.ISpriteInstance {},
	橋式起重機_操作解釋頁面2_上下左右: class extends self.ITextInstance {},
	橋式起重機_操作解釋頁面2_鎖2: class extends self.ITextInstance {},
	橋式起重機_操作解釋頁面2_鬆: class extends self.ITextInstance {},
	說明選單_說明文字: class extends self.ITextInstance {},
	橋式起重機_通關: class extends self.ITextInstance {},
	橋式起重機_導航欄: class extends self.ISpriteInstance {},
	橋式起重機_導航欄2: class extends self.ISpriteInstance {},
	場租費: class extends self.ITextInstance {},
	裝卸費: class extends self.ITextInstance {},
	冷凍櫃費用: class extends self.ITextInstance {},
	倉庫費用: class extends self.ITextInstance {},
	貨櫃清潔及維修費用: class extends self.ITextInstance {},
	理貨費: class extends self.ITextInstance {},
	解答: class extends self.ITextInstance {},
	是: class extends self.ITextInstance {},
	否: class extends self.ITextInstance {},
	場租費2: class extends self.ITextInstance {},
	冷凍櫃費用2: class extends self.ITextInstance {},
	冷凍櫃費用3: class extends self.ITextInstance {},
	BG: class extends self.ISpriteInstance {},
	拖車: class extends self.ISpriteInstance {},
	空櫃堆高機: class extends self.ISpriteInstance {},
	方向盤: class extends self.ISpriteInstance {},
	鍵盤: class extends self.IInstance {},
	地板: class extends self.ISpriteInstance {},
	空櫃堆高機_地圖: class extends self.ISpriteInstance {},
	拖車板車: class extends self.ISpriteInstance {},
	空櫃: class extends self.ISpriteInstance {},
	空櫃夾: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	鎖: class extends self.ISpriteInstance {},
	鬆: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	軌道式門式起重機_地圖_白邊: class extends self.ISpriteInstance {},
	輪胎式門式起重機_地圖: class extends self.ISpriteInstance {},
	輪型跨載機_地圖_白邊: class extends self.ISpriteInstance {},
	重櫃堆高機_地圖: class extends self.ISpriteInstance {},
	倉庫堆高機_地圖: class extends self.ISpriteInstance {},
	空櫃起重機_停車點: class extends self.ISpriteInstance {},
	船: class extends self.ISpriteInstance {},
	夾子: class extends self.ISpriteInstance {},
	繩子: class extends self.ISpriteInstance {},
	滑塊: class extends self.ISpriteInstance {},
	輪胎式門式起重機: class extends self.ISpriteInstance {},
	軌道式門式起重機_後: class extends self.ISpriteInstance {},
	貨櫃堆1: class extends self.ISpriteInstance {},
	非實體車: class extends self.ISpriteInstance {},
	軌道式門式起重機_側面: class extends self.ISpriteInstance {},
	輪胎式門式起重機_俯視: class extends self.ISpriteInstance {},
	拖車板車俯視: class extends self.ISpriteInstance {},
	貨櫃_俯視: class extends self.ISpriteInstance {},
	輪胎式門式起重機_側面: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	貨櫃堆_俯視: class extends self.ISpriteInstance {},
	輪型跨載機_側面: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	重櫃夾: class extends self.ISpriteInstance {},
	重櫃堆高機: class extends self.ISpriteInstance {},
	繩子2: class extends self.ISpriteInstance {},
	大標題: class extends self.ITextInputInstance {},
	標題: class extends self.ITextInstance {},
	按鈕: class extends self.IButtonInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	開始: class extends self.ITextInstance {},
	音頻: class extends self.IInstance {},
	視頻: class extends self.IWorldInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	說明icon: class extends self.ISpriteInstance {},
	目錄頁_CH1: class extends self.ISpriteInstance {},
	目錄頁_CH2: class extends self.ISpriteInstance {},
	目錄頁_CH3: class extends self.ISpriteInstance {},
	選擇章節: class extends self.ITextInstance {},
	目錄頁_CH1_B: class extends self.ITextInstance {},
	目錄頁_CH2_B: class extends self.ITextInstance {},
	目錄頁_CH3_B: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	鍵盤左: class extends self.ISpriteInstance {},
	倉庫堆高機: class extends self.ISpriteInstance {},
	倉庫堆高機_夾子: class extends self.ISpriteInstance {},
	沒載貨櫃的車_左側: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	裝卸費和理貨費_確認: class extends self.ISpriteInstance {},
	場租費_確認: class extends self.ISpriteInstance {},
	冷凍櫃費用_確認: class extends self.ISpriteInstance {},
	倉庫費用_確認: class extends self.ISpriteInstance {},
	貨櫃清潔及維修費用_確認: class extends self.ISpriteInstance {},
	理貨費_確認: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	說明: class extends self.ITextInstance {},
	體驗: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	門式起重機_測驗選項: class extends self.ITextInstance {},
	橋式起重機_測驗選項: class extends self.ITextInstance {},
	重櫃堆高機_測驗選項: class extends self.ITextInstance {},
	倉庫堆高機_測驗選項: class extends self.ITextInstance {},
	裝卸機_測驗選項: class extends self.ITextInstance {},
	輪型跨載機_測驗選項: class extends self.ITextInstance {},
	空櫃堆高機_測驗選項: class extends self.ITextInstance {},
	拖車_測驗選項: class extends self.ITextInstance {},
	按鈕底部樣式: class extends self.ISpriteInstance {},
	視頻2: class extends self.IWorldInstance {},
	滑動條: class extends self.ISliderBarInstance {},
	播放: class extends self.ISpriteInstance {},
	暫停: class extends self.ISpriteInstance {},
	大地圖: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	輪型跨載機_地圖2: class extends self.ISpriteInstance {},
	軌道式門式起重機_地圖: class extends self.ISpriteInstance {},
	空櫃堆高機側: class extends self.ISpriteInstance {},
	空櫃2: class extends self.ISpriteInstance {},
	空櫃3: class extends self.ISpriteInstance {},
	測驗: class extends self.ISpriteInstance {},
	滑鼠: class extends self.IInstance {},
	圈: class extends self.ISpriteInstance {},
	叉叉: class extends self.ISpriteInstance {},
	四題選擇_選項1: class extends self.ITextInstance {},
	四題選擇_選項2: class extends self.ITextInstance {},
	四題選擇_選項3: class extends self.ITextInstance {},
	四題選擇_選項4: class extends self.ITextInstance {},
	滑動條2: class extends self.ISliderBarInstance {},
	一號貨櫃人: class extends self.ISpriteInstance {},
	位圖字體: class extends self.ISpriteFontInstance {},
	回答: class extends self.ITextInstance {},
	圖標_選單背景: class extends self.ISpriteInstance {},
	圖標_選單說明: class extends self.ISpriteInstance {},
	進入體驗按鈕: class extends self.ISpriteInstance {},
	說明選單_標題: class extends self.ITextInstance {},
	說明選單_進入體驗按鈕: class extends self.ITextInstance {},
	分隔線: class extends self.ISpriteInstance {},
	貨櫃一問答_ans: class extends self.IArrayInstance {},
	沒載貨櫃的車_右側: class extends self.ISpriteInstance {},
	測驗icon: class extends self.ISpriteInstance {},
	Bg2: class extends self.ISpriteInstance {},
	重櫃堆高機_選項: class extends self.ISpriteInstance {},
	空櫃堆高機_選項: class extends self.ISpriteInstance {},
	倉庫堆高機_選項: class extends self.ISpriteInstance {},
	Bg3: class extends self.ISpriteInstance {},
	標題2: class extends self.ITextInstance {},
	地圖_橋式起重機_小標: class extends self.ITextInstance {},
	地圖_輪胎式門式起重機_小標: class extends self.ITextInstance {},
	導航欄背景: class extends self.ISpriteInstance {},
	輪胎式門式起重機_導航欄: class extends self.ISpriteInstance {},
	空櫃堆高機_導航欄: class extends self.ISpriteInstance {},
	重櫃堆高機_導航欄: class extends self.ISpriteInstance {},
	輪型跨載機_導航欄: class extends self.ISpriteInstance {},
	拖車_導航欄: class extends self.ISpriteInstance {},
	倉庫堆高機_導航欄: class extends self.ISpriteInstance {},
	軌道式門式起重機_導航欄: class extends self.ISpriteInstance {},
	地圖_空櫃堆高機_小標: class extends self.ITextInstance {},
	地圖_重櫃堆高機_小標: class extends self.ITextInstance {},
	地圖_輪型跨載機_小標: class extends self.ITextInstance {},
	地圖_拖車_小標: class extends self.ITextInstance {},
	地圖_軌道式門式起重機_小標: class extends self.ITextInstance {},
	地圖_倉庫堆高機_小標: class extends self.ITextInstance {},
	Bg4: class extends self.ISpriteInstance {},
	軌道式門式起重機_導航欄2: class extends self.ISpriteInstance {},
	倉庫堆高機_導航欄2: class extends self.ISpriteInstance {},
	輪胎式門式起重機_導航欄2: class extends self.ISpriteInstance {},
	空櫃堆高機_導航欄2: class extends self.ISpriteInstance {},
	重櫃堆高機_導航欄2: class extends self.ISpriteInstance {},
	輪型跨載機_導航欄2: class extends self.ISpriteInstance {},
	拖車_導航欄2: class extends self.ISpriteInstance {},
	貨櫃堆2: class extends self.ISpriteInstance {},
	重櫃堆高機_題目: class extends self.ISpriteInstance {},
	按鈕底部樣式_橋式起重機: class extends self.ISpriteInstance {},
	按鈕底部樣式_重櫃堆高機: class extends self.ISpriteInstance {},
	按鈕底部樣式_輪型跨載機: class extends self.ISpriteInstance {},
	按鈕底部樣式_拖車: class extends self.ISpriteInstance {},
	框: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	列表: class extends self.IListInstance {},
	人: class extends self.ISpriteInstance {},
	對話框: class extends self.ISpriteInstance {},
	next2: class extends self.ISpriteInstance {},
	選項1: class extends self.ITextInstance {},
	選項2: class extends self.ITextInstance {},
	選項3: class extends self.ITextInstance {},
	選項4: class extends self.ITextInstance {},
	選項5: class extends self.ITextInstance {},
	選項6: class extends self.ITextInstance {},
	選項7: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	櫃選: class extends self.ISpriteInstance {},
	按鈕底部樣式_1: class extends self.ISpriteInstance {},
	按鈕底部樣式_2: class extends self.ISpriteInstance {},
	按鈕底部樣式_3: class extends self.ISpriteInstance {},
	按鈕底部樣式_4: class extends self.ISpriteInstance {},
	按鈕底部樣式_5: class extends self.ISpriteInstance {},
	按鈕底部樣式_6: class extends self.ISpriteInstance {},
	裝卸費_框: class extends self.ISpriteInstance {},
	理貨費_框: class extends self.ISpriteInstance {},
	場租費_框: class extends self.ISpriteInstance {},
	場租費_框2: class extends self.ISpriteInstance {},
	場租費_框3: class extends self.ISpriteInstance {},
	場租費_框4: class extends self.ISpriteInstance {},
	冷凍櫃費_框: class extends self.ISpriteInstance {},
	清潔費_框: class extends self.ISpriteInstance {},
	維修費_框: class extends self.ISpriteInstance {},
	清潔費_框2: class extends self.ISpriteInstance {},
	清潔費_框3: class extends self.ISpriteInstance {},
	倉庫費_框: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	費用標籤_裝卸: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	SVG: class extends self.ISVGPictureInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	填答完成: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	選項8: class extends self.ITextInstance {},
	按鈕底部樣式_7: class extends self.ISpriteInstance {},
	貨櫃一作答: class extends self.IArrayInstance {},
	費用標籤_選中: class extends self.ISpriteInstance {},
	CH3_說明文字: class extends self.ITextInstance {},
	CH3_說明文字2: class extends self.ITextInstance {},
	進度燈: class extends self.ISpriteInstance {},
	進度燈2: class extends self.ISpriteInstance {},
	進度燈3: class extends self.ISpriteInstance {},
	進度燈4: class extends self.ISpriteInstance {},
	進度燈5: class extends self.ISpriteInstance {},
	進度燈6: class extends self.ISpriteInstance {},
	船圖: class extends self.ISpriteInstance {},
	箭頭: class extends self.ISpriteInstance {},
	電腦: class extends self.ISpriteInstance {},
	CH3_說明文字5: class extends self.ITextInstance {},
	貨櫃堆3: class extends self.ISpriteInstance {},
	CH3_說明文字6: class extends self.ITextInstance {},
	按鈕框2: class extends self.ISpriteInstance {},
	CH3_說明文字7: class extends self.ITextInstance {},
	電腦2: class extends self.ISpriteInstance {},
	信件: class extends self.ISpriteInstance {},
	卸船櫃數單: class extends self.ISpriteInstance {},
	備註: class extends self.ITextInstance {},
	重櫃堆高機_右: class extends self.ISpriteInstance {},
	貨站: class extends self.ISpriteInstance {},
	出口貨物證明單: class extends self.ISpriteInstance {},
	信件2: class extends self.ISpriteInstance {},
	C1: class extends self.ISpriteInstance {},
	C2: class extends self.ISpriteInstance {},
	C3: class extends self.ISpriteInstance {},
	出口小結: class extends self.ISpriteInstance {},
	進口_分估計稅: class extends self.ISpriteInstance {},
	進口_受理報關: class extends self.ISpriteInstance {},
	進口_放行: class extends self.ISpriteInstance {},
	進口_查驗: class extends self.ISpriteInstance {},
	進口_海關辦理項目: class extends self.ISpriteInstance {},
	進口_提貨: class extends self.ISpriteInstance {},
	進口_登稅繳稅: class extends self.ISpriteInstance {},
	進口_C1: class extends self.ISpriteInstance {},
	進口_C2: class extends self.ISpriteInstance {},
	進口_C3: class extends self.ISpriteInstance {},
	C1遮罩: class extends self.ISpriteInstance {},
	C2遮罩: class extends self.ISpriteInstance {},
	出口_分估: class extends self.ISpriteInstance {},
	出口_放行: class extends self.ISpriteInstance {},
	出口_裝船: class extends self.ISpriteInstance {},
	空格: class extends self.ISpriteInstance {},
	空格_C1: class extends self.ISpriteInstance {},
	空格_C2: class extends self.ISpriteInstance {},
	空格_C3: class extends self.ISpriteInstance {},
	勾勾: class extends self.ISpriteInstance {},
	勾勾2: class extends self.ISpriteInstance {},
	勾勾3: class extends self.ISpriteInstance {},
	勾勾4: class extends self.ISpriteInstance {},
	勾勾5: class extends self.ISpriteInstance {},
	勾勾6: class extends self.ISpriteInstance {},
	勾勾7: class extends self.ISpriteInstance {},
	費用標籤_理貨: class extends self.ISpriteInstance {},
	費用標籤_場租: class extends self.ISpriteInstance {},
	費用標籤_冷凍: class extends self.ISpriteInstance {},
	費用標籤_倉庫: class extends self.ISpriteInstance {},
	費用標籤_清修: class extends self.ISpriteInstance {},
	檢查清單: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	船2: class extends self.ISpriteInstance {},
	空氣牆: class extends self.ISpriteInstance {},
	手: class extends self.ISpriteInstance {},
	手2: class extends self.ISpriteInstance {},
	空櫃4: class extends self.ISpriteInstance {},
	上下: class extends self.ISpriteInstance {},
	貨櫃堆4: class extends self.ISpriteInstance {},
	橋式_體驗結束: class extends self.ISpriteInstance {},
	貨櫃堆5: class extends self.ISpriteInstance {},
	空格2: class extends self.ISpriteInstance {},
	說明選單_標題2: class extends self.ITextInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	bg_目錄: class extends self.ISpriteInstance {},
	上一頁: class extends self.ISpriteInstance {},
	按鈕框3: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	鍵盤上: class extends self.ISpriteInstance {},
	鍵盤下: class extends self.ISpriteInstance {},
	鍵盤右: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	CH2: class extends self.ISpriteInstance {},
	CH3: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	按鈕2: class extends self.IButtonInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	按鈕底部樣式_8: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	出口5船: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	空櫃堆高機_體驗結束: class extends self.ISpriteInstance {},
	軌_體驗結束: class extends self.ISpriteInstance {},
	輪_體驗結束: class extends self.ISpriteInstance {},
	倉庫堆高機背景: class extends self.ISpriteInstance {},
	輪胎_體驗結束: class extends self.ISpriteInstance {},
	重_體驗結束: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	倉_體驗結束: class extends self.ISpriteInstance {},
	按鈕底部樣式_輪型跨載機2: class extends self.ISpriteInstance {},
	拖車_右邊介面: class extends self.ISpriteInstance {},
	空櫃堆高機_右邊介面: class extends self.ISpriteInstance {},
	軌道式門式起重機_右邊介面: class extends self.ISpriteInstance {},
	重櫃堆高機_右邊介面: class extends self.ISpriteInstance {},
	倉庫堆高機_右邊介面: class extends self.ISpriteInstance {},
	第一章機具介紹_右邊介面: class extends self.ISpriteInstance {},
	跨載機_右邊介面: class extends self.ISpriteInstance {},
	輪胎式門式起重機_右邊介面: class extends self.ISpriteInstance {},
	橋式起重機_右邊介面: class extends self.ISpriteInstance {},
	進入體驗: class extends self.ISpriteInstance {},
	CH1: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	確認: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	進口3按鈕: class extends self.ISpriteInstance {},
	進口4: class extends self.ISpriteInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	Sprite141: class extends self.ISpriteInstance {},
	比對完成: class extends self.ISpriteInstance {},
	出口2按鈕: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	選1: class extends self.ISpriteInstance {},
	選3: class extends self.ISpriteInstance {},
	選2: class extends self.ISpriteInstance {},
	選4: class extends self.ISpriteInstance {},
	CH3_選2: class extends self.ISpriteInstance {},
	CH3_選1: class extends self.ISpriteInstance {},
	CH3_選3: class extends self.ISpriteInstance {},
	CH3_選4: class extends self.ISpriteInstance {},
	C3拖: class extends self.ISpriteInstance {},
	C1拖: class extends self.ISpriteInstance {},
	C2拖: class extends self.ISpriteInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	出口3按鈕: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	是2: class extends self.ISpriteInstance {},
	否2: class extends self.ISpriteInstance {},
	_20尺: class extends self.ISpriteInstance {},
	_30尺: class extends self.ISpriteInstance {},
	_40尺: class extends self.ISpriteInstance {},
	_45尺: class extends self.ISpriteInstance {},
	Sprite170: class extends self.ISpriteInstance {},
	重櫃_選: class extends self.ISpriteInstance {},
	輪型_選: class extends self.ISpriteInstance {},
	門式_選: class extends self.ISpriteInstance {},
	橋式_選: class extends self.ISpriteInstance {},
	Sprite175: class extends self.ISpriteInstance {},
	Sprite176: class extends self.ISpriteInstance {},
	Sprite177: class extends self.ISpriteInstance {},
	Sprite178: class extends self.ISpriteInstance {},
	叉叉2: class extends self.ISpriteInstance {},
	叉叉3: class extends self.ISpriteInstance {},
	拖標: class extends self.ISpriteInstance {},
	空標: class extends self.ISpriteInstance {},
	橋標: class extends self.ISpriteInstance {},
	胎標: class extends self.ISpriteInstance {},
	輪標: class extends self.ISpriteInstance {},
	重標: class extends self.ISpriteInstance {},
	倉標: class extends self.ISpriteInstance {},
	軌標: class extends self.ISpriteInstance {},
	開始測驗: class extends self.ISpriteInstance {},
	開始檢查: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	測驗結束: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	紅心1: class extends self.ISpriteInstance {},
	紅心2: class extends self.ISpriteInstance {},
	紅心3: class extends self.ISpriteInstance {},
	CH1_測驗說明: class extends self.ISpriteInstance {},
	小叉: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	裝卸費說明: class extends self.ISpriteInstance {},
	裝卸費說明2: class extends self.ISpriteInstance {},
	裝卸費說明3: class extends self.ISpriteInstance {},
	裝卸費說明4: class extends self.ISpriteInstance {},
	裝卸費說明5: class extends self.ISpriteInstance {},
	裝卸費說明6: class extends self.ISpriteInstance {},
	裝卸費說明7: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	擋1: class extends self.ISpriteInstance {},
	擋2: class extends self.ISpriteInstance {},
	CH2_說明文字: class extends self.ITextInstance {},
	CH2箭頭: class extends self.ISpriteInstance {},
	next3: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	裝卸費說明8: class extends self.ISpriteInstance {},
	_3岀: class extends self.ISpriteInstance {},
	C13: class extends self.ISpriteInstance {},
	第三章小選單: class extends self.ISpriteInstance {},
	拖車_測: class extends self.ISpriteInstance {},
	空櫃_測: class extends self.ISpriteInstance {},
	裝_測: class extends self.ISpriteInstance {},
	門_測: class extends self.ISpriteInstance {},
	橋_測: class extends self.ISpriteInstance {},
	輪跨_測: class extends self.ISpriteInstance {},
	重_測: class extends self.ISpriteInstance {},
	倉_測: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	手3: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	c1說明: class extends self.ISpriteInstance {},
	c2說明: class extends self.ISpriteInstance {},
	c3說明: class extends self.ISpriteInstance {},
	c1說明出: class extends self.ISpriteInstance {},
	c2說明出: class extends self.ISpriteInstance {},
	c3說明出: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	next4: class extends self.ISpriteInstance {},
	注視框: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	注視框2: class extends self.ISpriteInstance {},
	注視框3: class extends self.ISpriteInstance {},
	QRCode: class extends self.IQRCodeInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	QRCode2: class extends self.IQRCodeInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	上一頁2: class extends self.ISpriteInstance {},
	QRCode3: class extends self.IQRCodeInstance {},
	Internationalization: class extends self.IInstance {},
	Text10: class extends self.ITextInstance {},
	空櫃AR: class extends self.ISpriteInstance {},
	倉庫AR: class extends self.ISpriteInstance {},
	輪型AR: class extends self.ISpriteInstance {},
	拖車AR: class extends self.ISpriteInstance {},
	重櫃AR: class extends self.ISpriteInstance {},
	輪胎AR: class extends self.ISpriteInstance {},
	橋式AR: class extends self.ISpriteInstance {},
	軌道AR: class extends self.ISpriteInstance {},
	Text11: class extends self.ITextInstance {}
}